# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vSMCdmaSA0k6RhWQuChRn52nPXsOzOFs
"""

pip install --upgrade kiteconnect

!pip install -U pip setuptools

import logging
from kiteconnect import KiteConnect

kite = KiteConnect(api_key="your_api_key")
logging.basicConfig(level=logging.DEBUG)

"""# Redirect bold text the user to the login url obtained
# from kite.login_url(), and receive the request_token
# from the registered redirect url after the login flow.
# Once you have the request_token, obtain the access_token
# as follows.
"""

kite.login_url()

data = kite.generate_session("request_token_here", api_secret="your_secret")
kite.set_access_token(data["access_token"])

kite.holdings()

kite.positions()

#kite.ltp('NSE:INFY')
kite.quote('NSE:RELIANCE')

instruments = kite.instruments()

instruments

len(instruments)

instruments = kite.instruments("NSE")
for instrument in instruments:
    if instrument["tradingsymbol"] == "RELIANCE":
        print(instrument["instrument_token"])

from datetime import datetime

instrument_token = 738561  # RELIANCE NSE token
from_date = datetime(2024, 5, 1)
to_date = datetime(2024, 5, 15)
interval = "day"  # Options: "minute", "3minute", "5minute", "10minute", "15minute", "30minute", "60minute", "day"

data = kite.historical_data(instrument_token, from_date, to_date, interval)

for candle in data:
    print(candle)

